-- Fibre Construction: projects, receipts, invoices.
-- Money columns are numeric so totals are summed in SQL, not JavaScript floats.
-- Receipt files: receipts bucket, {project_id}/{expense_id}.jpg
-- Thumbnails: receipts bucket, {project_id}/thumbs/{expense_id}.jpg
-- Invoice files: invoices bucket, {project_id}/{invoice_id}

create extension if not exists pg_trgm with schema extensions;

-- ---------------------------------------------------------------------------
-- Access gate. Today any signed-in user belongs to the company.
-- Add role checks in this function when multi-user roles are introduced.
-- ---------------------------------------------------------------------------

create or replace function public.has_company_access()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select auth.uid() is not null;
$$;

comment on function public.has_company_access() is
  'Single-company gate. Any authenticated user is allowed. Add role checks here when multi-user roles are introduced.';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text,
  client_name text,
  client_email text,
  builder_fee_percent numeric not null default 15,
  retainage_percent numeric not null default 0,
  status text not null default 'active',
  contract_amount numeric(12, 2),
  share_token text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint projects_name_not_blank check (char_length(trim(name)) > 0),
  constraint projects_status_check check (status in ('active', 'completed', 'on_hold')),
  constraint projects_builder_fee_percent_range check (
    builder_fee_percent >= 0 and builder_fee_percent <= 100
  ),
  constraint projects_retainage_percent_range check (
    retainage_percent >= 0 and retainage_percent <= 100
  ),
  constraint projects_share_token_key unique (share_token)
);

create table public.categories (
  id integer generated by default as identity primary key,
  code integer not null,
  name text not null,
  sort_order integer not null,
  is_active boolean not null default true,
  keywords text[] not null default '{}',
  constraint categories_code_key unique (code),
  constraint categories_code_positive check (code > 0),
  constraint categories_name_not_blank check (char_length(trim(name)) > 0)
);

create table public.project_budgets (
  project_id uuid not null references public.projects (id) on delete cascade,
  category_id integer not null references public.categories (id) on delete restrict,
  budget_amount numeric(12, 2) not null,
  constraint project_budgets_pkey primary key (project_id, category_id),
  constraint project_budgets_amount_nonnegative check (budget_amount >= 0)
);

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  invoice_number text not null,
  invoice_date date not null default current_date,
  subtotal numeric(12, 2) not null default 0,
  builder_fee numeric(12, 2) not null default 0,
  retainage numeric(12, 2) not null default 0,
  total_amount numeric(12, 2) not null default 0,
  status text not null default 'pending',
  amount_paid numeric(12, 2) not null default 0,
  paid_date date,
  file_path text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint invoices_project_number_key unique (project_id, invoice_number),
  constraint invoices_number_not_blank check (char_length(trim(invoice_number)) > 0),
  constraint invoices_status_check check (
    status in ('pending', 'paid', 'partially_paid', 'void')
  ),
  constraint invoices_amount_paid_nonnegative check (amount_paid >= 0)
);

comment on column public.invoices.subtotal is
  'Sum of linked verified expenses. Maintained by recalculate_invoice().';
comment on column public.invoices.total_amount is
  'Amount written on the invoice document. Not overwritten by recalculate_invoice().';
comment on column public.invoices.file_path is
  'Storage path in the invoices bucket.';

create table public.expenses (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  category_id integer references public.categories (id) on delete restrict,
  vendor text,
  expense_date date,
  amount numeric(12, 2) not null default 0,
  receipt_number text,
  description text,
  payment_method text,
  receipt_file_path text not null,
  receipt_file_hash text not null,
  receipt_thumbnail_path text,
  split_group_id uuid,
  invoice_id uuid references public.invoices (id) on delete set null,
  ai_extracted jsonb,
  ai_suggested_category_ids integer[],
  ai_confidence numeric,
  verification_status text not null default 'needs_review',
  duplicate_of uuid references public.expenses (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null,
  constraint expenses_verification_status_check check (
    verification_status in ('needs_review', 'verified', 'flagged')
  ),
  constraint expenses_ai_confidence_range check (
    ai_confidence is null or (ai_confidence >= 0 and ai_confidence <= 1)
  ),
  constraint expenses_receipt_hash_sha256 check (receipt_file_hash ~ '^[0-9a-f]{64}$'),
  constraint expenses_duplicate_not_self check (
    duplicate_of is null or duplicate_of <> id
  ),
  constraint expenses_verified_requires_fields check (
    verification_status <> 'verified'
    or (
      category_id is not null
      and expense_date is not null
      and vendor is not null
      and char_length(trim(vendor)) > 0
    )
  )
);

comment on column public.expenses.receipt_file_path is
  'Private receipts bucket path: {project_id}/{expense_id}.jpg';
comment on column public.expenses.receipt_thumbnail_path is
  'Private receipts bucket path: {project_id}/thumbs/{expense_id}.jpg';
comment on column public.expenses.receipt_file_hash is
  'SHA-256 hex of the original file. Unsplit rows are unique per project. Split rows may reuse a hash only inside the same split_group_id.';

create table public.expense_audit (
  id uuid primary key default gen_random_uuid(),
  expense_id uuid not null references public.expenses (id) on delete cascade,
  changed_by uuid references auth.users (id) on delete set null,
  changed_at timestamptz not null default now(),
  field text not null,
  old_value text,
  new_value text
);

-- Hard block: one unsplit file hash per project.
create unique index expenses_unsplit_receipt_hash_uidx
  on public.expenses (project_id, receipt_file_hash)
  where split_group_id is null;

create index expenses_project_id_idx on public.expenses (project_id);
create index expenses_invoice_id_idx on public.expenses (invoice_id);
create index expenses_category_id_idx on public.expenses (category_id);
create index expenses_project_receipt_hash_idx
  on public.expenses (project_id, receipt_file_hash);
create index expenses_project_verification_idx
  on public.expenses (project_id, verification_status);
create index expenses_soft_duplicate_idx
  on public.expenses (project_id, amount, expense_date);
create index expenses_receipt_number_idx
  on public.expenses (project_id, receipt_number);
create index expenses_vendor_trgm_idx
  on public.expenses using gin (vendor extensions.gin_trgm_ops);
create index invoices_project_id_idx on public.invoices (project_id);
create index expense_audit_expense_id_idx on public.expense_audit (expense_id);
create index categories_sort_order_idx on public.categories (sort_order);

-- ---------------------------------------------------------------------------
-- Receipt hash: split rows may share a hash only inside one split group.
-- ---------------------------------------------------------------------------

create or replace function public.enforce_receipt_hash_uniqueness()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  existing_id uuid;
  existing_created timestamptz;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(new.project_id::text || ':' || new.receipt_file_hash, 0)
  );

  select e.id, e.created_at
    into existing_id, existing_created
  from public.expenses e
  where e.project_id = new.project_id
    and e.receipt_file_hash = new.receipt_file_hash
    and e.id is distinct from new.id
    and (
      e.split_group_id is distinct from new.split_group_id
      or (e.split_group_id is null and new.split_group_id is null)
    )
  limit 1;

  if found then
    raise exception 'Duplicate receipt — already uploaded on %',
      to_char(existing_created at time zone 'UTC', 'YYYY-MM-DD')
      using
        errcode = '23505',
        detail = existing_id::text;
  end if;

  return new;
end;
$$;

create or replace function public.prevent_expense_invoice_relink()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  existing_number text;
begin
  if old.invoice_id is not null
     and new.invoice_id is not null
     and old.invoice_id is distinct from new.invoice_id then
    select i.invoice_number
      into existing_number
    from public.invoices i
    where i.id = old.invoice_id;

    raise exception 'This expense is already on invoice %',
      coalesce(existing_number, old.invoice_id::text)
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function public.log_expense_changes()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  col text;
  old_json jsonb := to_jsonb(old);
  new_json jsonb := to_jsonb(new);
  tracked text[] := array[
    'category_id',
    'vendor',
    'expense_date',
    'amount',
    'receipt_number',
    'description',
    'payment_method',
    'invoice_id',
    'verification_status',
    'duplicate_of'
  ];
begin
  foreach col in array tracked loop
    if old_json -> col is distinct from new_json -> col then
      insert into public.expense_audit (
        expense_id,
        changed_by,
        field,
        old_value,
        new_value
      )
      values (
        new.id,
        auth.uid(),
        col,
        old_json ->> col,
        new_json ->> col
      );
    end if;
  end loop;

  return new;
end;
$$;

-- subtotal = verified linked expenses
-- builder_fee = round(subtotal * builder_fee_percent / 100, 2)
-- retainage = round((subtotal + builder_fee) * retainage_percent / 100, 2)
-- total_amount is the figure printed on the invoice and is left unchanged.
create or replace function public.recalculate_invoice(target uuid)
returns void
language plpgsql
set search_path = public
as $$
declare
  spent numeric(12, 2);
  fee_pct numeric;
  ret_pct numeric;
  fee numeric(12, 2);
  ret numeric(12, 2);
begin
  if target is null
     or current_setting('app.skip_invoice_refresh', true) = 'on' then
    return;
  end if;

  select coalesce(sum(e.amount), 0)
    into spent
  from public.expenses e
  where e.invoice_id = target
    and e.verification_status = 'verified';

  select p.builder_fee_percent, p.retainage_percent
    into fee_pct, ret_pct
  from public.invoices i
  join public.projects p on p.id = i.project_id
  where i.id = target;

  if not found then
    return;
  end if;

  fee := round(spent * fee_pct / 100, 2);
  ret := round((spent + fee) * ret_pct / 100, 2);

  update public.invoices
  set
    subtotal = spent,
    builder_fee = fee,
    retainage = ret
  where id = target
    and (
      subtotal is distinct from spent
      or builder_fee is distinct from fee
      or retainage is distinct from ret
    );
end;
$$;

create or replace function public.touch_invoice_amounts()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_setting('app.skip_invoice_refresh', true) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform public.recalculate_invoice(old.invoice_id);
    return old;
  end if;

  if tg_op = 'UPDATE' and old.invoice_id is distinct from new.invoice_id then
    perform public.recalculate_invoice(old.invoice_id);
  end if;

  perform public.recalculate_invoice(new.invoice_id);
  return new;
end;
$$;

create or replace function public.refresh_project_invoice_amounts()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  inv uuid;
begin
  if new.builder_fee_percent is distinct from old.builder_fee_percent
     or new.retainage_percent is distinct from old.retainage_percent then
    for inv in
      select i.id
      from public.invoices i
      where i.project_id = new.id
    loop
      perform public.recalculate_invoice(inv);
    end loop;
  end if;

  return new;
end;
$$;

-- Null expense links before the invoice row is removed so the refresh
-- trigger does not update a row that is mid-delete.
create or replace function public.unlink_invoice_expenses()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  perform set_config('app.skip_invoice_refresh', 'on', true);
  update public.expenses
  set invoice_id = null
  where invoice_id = old.id;
  perform set_config('app.skip_invoice_refresh', 'off', true);
  return old;
end;
$$;

create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

create trigger projects_refresh_invoice_amounts
after update of builder_fee_percent, retainage_percent on public.projects
for each row execute function public.refresh_project_invoice_amounts();

create trigger invoices_set_updated_at
before update on public.invoices
for each row execute function public.set_updated_at();

create trigger invoices_unlink_expenses
before delete on public.invoices
for each row execute function public.unlink_invoice_expenses();

create trigger expenses_set_updated_at
before insert or update on public.expenses
for each row execute function public.set_updated_at();

create trigger expenses_enforce_receipt_hash
before insert or update of project_id, receipt_file_hash, split_group_id
on public.expenses
for each row execute function public.enforce_receipt_hash_uniqueness();

create trigger expenses_prevent_invoice_relink
before update of invoice_id on public.expenses
for each row execute function public.prevent_expense_invoice_relink();

create trigger expenses_log_changes
after update on public.expenses
for each row execute function public.log_expense_changes();

create trigger expenses_refresh_invoice_amounts
after insert or update of amount, invoice_id, verification_status or delete
on public.expenses
for each row execute function public.touch_invoice_amounts();

-- ---------------------------------------------------------------------------
-- Views (security invoker: RLS on the base tables applies)
-- ---------------------------------------------------------------------------

create view public.v_expense_rows
with (security_invoker = true) as
select
  e.id,
  e.project_id,
  e.category_id,
  c.code as category_code,
  c.name as category_name,
  c.sort_order as category_sort_order,
  e.vendor,
  e.expense_date,
  e.amount,
  e.receipt_number,
  e.description,
  e.payment_method,
  e.receipt_file_path,
  e.receipt_file_hash,
  e.receipt_thumbnail_path,
  e.split_group_id,
  e.invoice_id,
  i.invoice_number,
  i.invoice_date,
  i.status as invoice_record_status,
  i.total_amount as invoice_total_amount,
  i.file_path as invoice_file_path,
  case
    when e.invoice_id is null then 'not_invoiced'
    else i.status
  end as invoice_status,
  e.ai_extracted,
  e.ai_suggested_category_ids,
  e.ai_confidence,
  e.verification_status,
  e.duplicate_of,
  e.created_at,
  e.updated_at,
  e.created_by
from public.expenses e
left join public.categories c on c.id = e.category_id
left join public.invoices i on i.id = e.invoice_id;

comment on view public.v_expense_rows is
  'Expense joined to category and invoice. invoice_status is not_invoiced when invoice_id is null; otherwise the invoice status.';

create view public.v_project_category_totals
with (security_invoker = true) as
select
  p.id as project_id,
  c.id as category_id,
  c.code,
  c.name,
  c.sort_order,
  c.is_active,
  coalesce(
    sum(e.amount) filter (where e.verification_status = 'verified'),
    0
  )::numeric(12, 2) as total_spent,
  pb.budget_amount as budget,
  (
    case
      when pb.budget_amount is null then null
      else pb.budget_amount - coalesce(
        sum(e.amount) filter (where e.verification_status = 'verified'),
        0
      )
    end
  )::numeric(12, 2) as variance,
  count(e.id)::integer as receipt_count
from public.projects p
cross join public.categories c
left join public.project_budgets pb
  on pb.project_id = p.id
  and pb.category_id = c.id
left join public.expenses e
  on e.project_id = p.id
  and e.category_id = c.id
group by
  p.id,
  c.id,
  c.code,
  c.name,
  c.sort_order,
  c.is_active,
  pb.budget_amount;

comment on view public.v_project_category_totals is
  'Every category for every project, ordered by categories.sort_order in the app. total_spent is verified expenses only. variance is budget minus that spent amount.';

create view public.v_project_summary
with (security_invoker = true) as
with expense_totals as (
  select
    e.project_id,
    coalesce(
      sum(e.amount) filter (where e.verification_status = 'verified'),
      0
    )::numeric(12, 2) as total_spent,
    coalesce(
      sum(e.amount) filter (
        where e.verification_status = 'verified'
          and e.invoice_id is not null
          and i.status is distinct from 'void'
      ),
      0
    )::numeric(12, 2) as total_invoiced,
    coalesce(
      sum(e.amount) filter (
        where e.verification_status = 'verified'
          and e.invoice_id is null
      ),
      0
    )::numeric(12, 2) as total_not_invoiced,
    count(*)::integer as receipt_count,
    count(*) filter (where e.verification_status = 'needs_review')::integer
      as needs_review_count
  from public.expenses e
  left join public.invoices i on i.id = e.invoice_id
  group by e.project_id
),
invoice_totals as (
  select
    project_id,
    coalesce(
      sum(amount_paid) filter (where status <> 'void'),
      0
    )::numeric(12, 2) as total_paid,
    coalesce(
      sum(greatest(total_amount - amount_paid, 0)) filter (
        where status in ('pending', 'partially_paid')
      ),
      0
    )::numeric(12, 2) as total_pending
  from public.invoices
  group by project_id
)
select
  p.id as project_id,
  p.name,
  p.address,
  p.client_name,
  p.client_email,
  p.status,
  p.builder_fee_percent,
  p.retainage_percent,
  coalesce(et.total_spent, 0)::numeric(12, 2) as total_spent,
  coalesce(et.total_invoiced, 0)::numeric(12, 2) as total_invoiced,
  coalesce(et.total_not_invoiced, 0)::numeric(12, 2) as total_not_invoiced,
  coalesce(it.total_paid, 0)::numeric(12, 2) as total_paid,
  coalesce(it.total_pending, 0)::numeric(12, 2) as total_pending,
  coalesce(et.receipt_count, 0)::integer as receipt_count,
  coalesce(et.needs_review_count, 0)::integer as needs_review_count,
  round(
    coalesce(et.total_spent, 0) * p.builder_fee_percent / 100,
    2
  )::numeric(12, 2) as builder_fee_amount
from public.projects p
left join expense_totals et on et.project_id = p.id
left join invoice_totals it on it.project_id = p.id;

comment on view public.v_project_summary is
  'Per project. Spent, invoiced, and not-invoiced amounts are verified expense totals. Paid and pending come from invoice payments. builder_fee_amount is total_spent times the project fee percent.';

-- ---------------------------------------------------------------------------
-- Category master list. code = sort_order = position. Display as "code – name".
-- ---------------------------------------------------------------------------

insert into public.categories (id, code, name, sort_order, is_active, keywords)
values
  (1, 1, 'Architectural', 1, true, array['architect', 'architectural', 'blueprint', 'drawings', 'design']),
  (2, 2, 'Engineering', 2, true, array['engineer', 'structural', 'civil', 'geotechnical', 'mechanical']),
  (3, 3, 'Legal', 3, true, array['attorney', 'lawyer', 'legal', 'closing']),
  (4, 4, 'Permits', 4, true, array['building permit', 'permit']),
  (5, 5, 'Surveying', 5, true, array['survey', 'surveyor', 'stakeout', 'boundary']),
  (6, 6, 'Insurance', 6, true, array['insurance', 'builder risk', 'liability', 'premium']),
  (7, 7, 'Site Plans', 7, true, array['site plan', 'plot plan']),
  (8, 8, 'Temporary Fencing', 8, true, array['temp fence', 'temporary fence', 'silt fence', 'construction fence']),
  (9, 9, 'Equipment Rental', 9, true, array['equipment rental', 'excavator rental', 'scissor lift', 'bobcat rental', 'rented']),
  (10, 10, 'Dumpsters', 10, true, array['dumpster', 'roll-off', 'rolloff', 'waste container']),
  (11, 11, 'Excavation / Grading', 11, true, array['excavation', 'grading', 'dirt work', 'cut and fill']),
  (12, 12, 'Foundation', 12, true, array['foundation', 'footing', 'rebar', 'slab', 'stem wall']),
  (13, 13, 'Framing', 13, true, array['framing', 'framer', 'frame labor']),
  (14, 14, 'Roofing', 14, true, array['roof', 'roofing', 'shingles']),
  (15, 15, 'HVAC', 15, true, array['hvac', 'heating', 'air conditioning', 'furnace', 'duct']),
  (16, 16, 'Plumbing', 16, true, array['plumber', 'plumbing']),
  (17, 17, 'Electrical', 17, true, array['electrician', 'electrical', 'wiring', 'panel']),
  (18, 18, 'Drywall', 18, true, array['drywall', 'sheetrock', 'gypsum', 'taping']),
  (19, 19, 'Insulation', 19, true, array['insulation', 'spray foam', 'fiberglass']),
  (20, 20, 'Painting', 20, true, array['paint', 'painter', 'staining']),
  (21, 21, 'Flooring', 21, true, array['flooring', 'hardwood', 'carpet', 'lvp', 'laminate']),
  (22, 22, 'Tile', 22, true, array['tile', 'tiling', 'backsplash']),
  (23, 23, 'Kitchen Cabinets', 23, true, array['kitchen cabinet', 'kitchen cabinets']),
  (24, 24, 'Bathroom Cabinets', 24, true, array['bathroom cabinet', 'vanity cabinet', 'bath cabinet']),
  (25, 25, 'Kitchen Countertops', 25, true, array['kitchen countertop', 'kitchen quartz', 'kitchen granite']),
  (26, 26, 'Bathroom Vanity Tops', 26, true, array['vanity top', 'bathroom vanity', 'bath countertop']),
  (27, 27, 'Appliances', 27, true, array['appliance', 'refrigerator', 'dishwasher', 'range', 'microwave', 'oven']),
  (28, 28, 'Doors', 28, true, array['door', 'doors', 'prehung']),
  (29, 29, 'Windows', 29, true, array['window', 'windows', 'glazing']),
  (30, 30, 'Siding', 30, true, array['siding', 'hardie', 'vinyl siding']),
  (31, 31, 'Gutters', 31, true, array['gutter', 'gutters', 'downspout']),
  (32, 32, 'Trim / Millwork', 32, true, array['trim', 'millwork', 'baseboard', 'casing', 'crown']),
  (33, 33, 'Lumber', 33, true, array['lumber', 'plywood', 'osb', 'studs', '2x4']),
  (34, 34, 'Concrete', 34, true, array['concrete', 'driveway', 'sidewalk', 'patio', 'walkway']),
  (35, 35, 'Masonry / Brick', 35, true, array['masonry', 'brick', 'block', 'stone veneer']),
  (36, 36, 'Landscaping', 36, true, array['landscape', 'landscaping', 'sod', 'irrigation']),
  (37, 37, 'Garage', 37, true, array['garage door', 'garage']),
  (38, 38, 'Cabinets / Cabinet Hardware', 38, true, array['cabinet hardware', 'knob', 'pull', 'hinge']),
  (39, 39, 'Countertops', 39, true, array['countertop', 'quartz', 'granite']),
  (40, 40, 'Fixtures', 40, true, array['fixture', 'faucet', 'toilet', 'light fixture', 'sink']),
  (41, 41, 'General Labor', 41, true, array['general labor', 'day labor']),
  (42, 42, 'Subcontractors', 42, true, array['subcontractor', 'sub']),
  (43, 43, 'Materials', 43, true, array['materials', 'supplies']),
  (44, 44, 'Equipment / Tools', 44, true, array['tool', 'tools', 'equipment purchase']),
  (45, 45, 'Supervision', 45, true, array['supervision', 'superintendent']),
  (46, 46, 'Cleaning', 46, true, array['cleaning', 'final clean']),
  (47, 47, 'Construction Management', 47, true, array['construction management', 'project management']),
  (48, 48, 'Safety', 48, true, array['safety', 'ppe']),
  (49, 49, 'Temporary Utilities', 49, true, array['temp power', 'temporary power', 'temp water', 'power pole']),
  (50, 50, 'Utilities', 50, true, array['utility bill', 'electric bill', 'water bill', 'gas bill']),
  (51, 51, 'Inspections', 51, true, array['inspection', 'inspector']),
  (52, 52, 'Delivery / Freight', 52, true, array['delivery', 'freight', 'shipping']),
  (53, 53, 'Permits & Fees', 53, true, array['impact fee', 'tap fee', 'plan review', 'application fee']),
  (54, 54, 'Office / Administrative', 54, true, array['office', 'administrative', 'postage', 'copies']),
  (55, 55, 'Miscellaneous', 55, true, array['miscellaneous', 'misc'])
on conflict (id) do update
set
  code = excluded.code,
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  keywords = excluded.keywords;

select setval(
  pg_get_serial_sequence('public.categories', 'id'),
  (select max(id) from public.categories)
);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.projects enable row level security;
alter table public.categories enable row level security;
alter table public.project_budgets enable row level security;
alter table public.invoices enable row level security;
alter table public.expenses enable row level security;
alter table public.expense_audit enable row level security;

create policy projects_authenticated_all
  on public.projects
  for all
  to authenticated
  using (public.has_company_access())
  with check (public.has_company_access());

create policy categories_authenticated_all
  on public.categories
  for all
  to authenticated
  using (public.has_company_access())
  with check (public.has_company_access());

create policy project_budgets_authenticated_all
  on public.project_budgets
  for all
  to authenticated
  using (public.has_company_access())
  with check (public.has_company_access());

create policy invoices_authenticated_all
  on public.invoices
  for all
  to authenticated
  using (public.has_company_access())
  with check (public.has_company_access());

create policy expenses_authenticated_all
  on public.expenses
  for all
  to authenticated
  using (public.has_company_access())
  with check (public.has_company_access());

create policy expense_audit_select
  on public.expense_audit
  for select
  to authenticated
  using (public.has_company_access());

create policy expense_audit_insert
  on public.expense_audit
  for insert
  to authenticated
  with check (public.has_company_access());

grant usage on schema public to authenticated, service_role;

grant select, insert, update, delete on
  public.projects,
  public.categories,
  public.project_budgets,
  public.invoices,
  public.expenses
to authenticated;

grant select, insert on public.expense_audit to authenticated;

grant select on
  public.v_expense_rows,
  public.v_project_category_totals,
  public.v_project_summary
to authenticated;

grant usage, select on sequence public.categories_id_seq to authenticated;

grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

grant execute on function public.has_company_access() to authenticated, service_role;
grant execute on function public.recalculate_invoice(uuid) to authenticated, service_role;

revoke all on table
  public.projects,
  public.categories,
  public.project_budgets,
  public.invoices,
  public.expenses,
  public.expense_audit,
  public.v_expense_rows,
  public.v_project_category_totals,
  public.v_project_summary
from anon;

revoke all on sequence public.categories_id_seq from anon;

-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'receipts',
    'receipts',
    false,
    20971520,
    array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
  ),
  (
    'invoices',
    'invoices',
    false,
    20971520,
    array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
  )
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy receipts_select_authenticated
  on storage.objects
  for select
  to authenticated
  using (bucket_id = 'receipts' and public.has_company_access());

create policy receipts_insert_authenticated
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'receipts' and public.has_company_access());

create policy receipts_update_authenticated
  on storage.objects
  for update
  to authenticated
  using (bucket_id = 'receipts' and public.has_company_access())
  with check (bucket_id = 'receipts' and public.has_company_access());

create policy receipts_delete_authenticated
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'receipts' and public.has_company_access());

create policy invoices_select_authenticated
  on storage.objects
  for select
  to authenticated
  using (bucket_id = 'invoices' and public.has_company_access());

create policy invoices_insert_authenticated
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'invoices' and public.has_company_access());

create policy invoices_update_authenticated
  on storage.objects
  for update
  to authenticated
  using (bucket_id = 'invoices' and public.has_company_access())
  with check (bucket_id = 'invoices' and public.has_company_access());

create policy invoices_delete_authenticated
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'invoices' and public.has_company_access());

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

alter table public.expenses replica identity full;
alter table public.invoices replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'expenses'
    ) then
      alter publication supabase_realtime add table public.expenses;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'invoices'
    ) then
      alter publication supabase_realtime add table public.invoices;
    end if;
  end if;
end $$;
